myhomework17/mall/urls.py
from django.urls import path
from mall import views

app_name = 'mall'

urlpatterns = [
    # path(루트(주소))를 만들어 줌, 링크를 클릭했을 때 호출 할 뷰함수, url reverse때 이용하는 이름)
    path('', views.cloth_list, name="cloth_list"),
    path('<int:pk>/', views.cloth_detail, name="cloth_detail"),
    path('new/', views.cloth_new, name="cloth_new"),
    path('<int:pk>/edit/', views.cloth_edit, name="cloth_edit"),
    path('tags/<str:tag_category>', views.tag_detail, name="tag_detail"),
]

myhomework17/myhomework17/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

def root(request):
    return redirect("mall:cloth_list")


urlpatterns = [
    path('admin/', admin.site.urls),
    path('mall/', include('mall.urls')),
    path('', root, name="root"),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__', include(debug_toolbar.urls)),
    ]

myhomework17/mall/models.py
from django.db import models


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Cloth(TimestampedModel):
    name = models.CharField(max_length=20, db_index=True)
    color = models.CharField(max_length=50)
    size = models.CharField(max_length=10)
    price = models.PositiveIntegerField()
    content = models.TextField()
    photo = models.ImageField()
    tag_set = models.ManyToManyField('Tag', blank=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "상품"
        verbose_name_plural = "상품목록"


class Review(TimestampedModel):
    cloth = models.ForeignKey(Cloth, on_delete=models.CASCADE)
    author_name = models.CharField(max_length=20)
    message = models.TextField()

    class Meta:
        verbose_name = "리뷰"
        verbose_name_plural = "리뷰목록"


class Tag(TimestampedModel):
    category = models.CharField(max_length=10, db_index=True)

    def __str__(self) -> str:
        return self.category

    class Meta:
        verbose_name = "태그"
        verbose_name_plural = "태그목록"

myhomework17/mall/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from mall.models import Cloth
from mall.form import ClothForm


def cloth_list(request: HttpRequest) -> HttpResponse:
    qs = Cloth.objects.all()
    qs = qs.order_by("-pk")
    q = request.GET.get("q", "")
    if q:
        qs = qs.filter(name__icontains=q)
    return render(request, "mall/cloth_list.html", {
        "cloth_list":qs,
    })

def cloth_detail(request: HttpRequest, pk: int) -> HttpResponse:
    cloth = Cloth.objects.get(pk=pk)
    review_list = cloth.review_set.all()
    tag_list = cloth.tag_set.all()
    return render(request, "mall/cloth_detail.html", {
        "cloth": cloth,
        "review_list": review_list,
        "tag_list": tag_list,
    })


def cloth_new(request: HttpRequest) -> HttpResponse:
    # raise NotImplementedError("곧 구현할 예정")
    if request.method == "POST":
         form = ClothForm(request.POST, request.FILES)
         if form.is_valid():
             saved_post = form.save()
             # shop_detail 뷰를 구현했다면,
             return redirect("mall:cloth_detail", saved_post.pk)
    else:
        form = ClothForm()
    return render(request, "mall/cloth_form.html", {
        "form": form,
    })


def cloth_edit(request: HttpRequest, pk: int) -> HttpResponse:
    cloth = get_object_or_404(Cloth, pk=pk)
    if request.method == "POST":
         form = ClothForm(request.POST, request.FILES, instance=cloth)
         if form.is_valid():
             saved_post = form.save()
             return redirect("mall:cloth_detail", saved_post.pk)
    else:
        form = ClothForm(instance=cloth)
    return render(request, "mall/cloth_form.html", {
        "form": form,
    })


def tag_detail(request: HttpRequest, tag_category: str) -> HttpResponse:
    qs = Cloth.objects.all()
    qs = qs.filter(tag_set__category=tag_category)
    return render(request, "mall/tag_detail.html", {
        "tag_category": tag_category,
        "cloth_list": qs,
    })

myhomework17/mall/templates/mall/cloth_detail.html
{% extends "mall/layout.html" %}

{% block content %}
    <h2>{{ cloth.name }}</h2>

    <p>
    태그:
    {% for tag in tag_list %}
        <a href="{% url "mall:tag_detail" tag.category%}" class="badge bg-success">
         {{ tag.category }}
        </a>
    {% endfor %}

    </p>

    <img src="{{ cloth.photo.url }}"
         alt="{{ cloth.name }}">

    {{ cloth.content|linebreaks }}

    <h3>리뷰</h3>
    <ul>
        {% for review in review_list %}
            <li>
                {{ review.message }}
                by {{ review.author_name }}
                at {{ review.created_at }}
            </li>
        {% endfor %}

    </ul>


    <a href="{% url "mall:cloth_list" %}">
        목록으로
    </a>
    <a href="{% url "mall:cloth_edit" cloth.pk %}">수정하기</a>

{% endblock %}

myhomework17/mall/templates/mall/cloth_form.html
{% extends "mall/layout.html" %}
{% load bootstrap5 %}

{% block content %}
    <h2>Cloth Form</h2>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="저장하기">
    </form>

{% endblock %}

myhomework17/mall/templates/mall/cloth_list.html
{% extends "mall/layout.html" %}

{% block content %}
    <div class="row">
        {% for cloth in cloth_list %}
            <div class="col-sm-3">
                <div class="card my-3">
                    <img src="{{ cloth.photo.url }}"
                         class="card-img-top"
                         alt="{{ cloth.name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ cloth.name }}</h5>
                        <p class="card-text">
                            {{ cloth.colot }}
                        </p>
                        <p class="card-text">
                            {{ cloth.price }}원
                        </p>
                        <a href="{% url "mall:cloth_detail" cloth.pk %}"
                           class="btn btn-primary">상세보기</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

myhomework17/mall/templates/mall/layout.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>몰 입어도 이쁜 몰</title>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <script src="//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    <header class="p-3 bg-dark text-white">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <h5>몰 입어도 이쁜 몰</h5>
                    <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                        <use xlink:href="#bootstrap"></use>
                    </svg>
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url "mall:cloth_list" %}" class="nav-link px-2 text-secondary">
                        Home
                    </a></li>
                    <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">About</a></li>
                </ul>

                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                    <input type="text" name="q" value="{{ request.GET.q }}"
                           class="form-control form-control-dark"
                           placeholder="검색어를 입력해주세요."
                           aria-label="Search">
                </form>

                <div class="text-end">
                    <a href="{% url "mall:cloth_new" %}" class="btn btn-outline-light me-2">
                        상품추가
                    </a>
                    <button type="button" class="btn btn-warning">Sign-up</button>
                </div>
            </div>
        </div>
    </header>
    {% block content %}
    {% endblock %}

    <hr/>
    &copy; 2021. 2mall company.
</div>

</body>
</html>

myhomework17/mall/templates/mall/tag_detail.html
{% extends "mall/layout.html" %}

{% block content %}
    <h2>{{ tag.category }}</h2>
    {% for cloth in cloth_list %}
        <div>
            <a href="{% url "mall:cloth_detail" cloth.pk %}">
                {{ cloth.name }}
            </a>
        </div>
    {% endfor %}

{% endblock %}