mydjango23/blog/urls.py
from django.urls import path

# from blog.views import cbv as views

from blog.views import fbv as views

app_name = "blog"

urlpatterns = [
    path('', views.post_list, name="post_list"),
    path('<int:pk>/', views.post_detail, name="post_detail"),
    path('new/', views.post_new, name="post_new"),
    path('<int:pk>/edit/', views.post_edit, name="post_edit"),
    path('<int:pk>/delete/', views.post_delete, name="post_delete"),
    path("subscriber/", views.subscriber_new, name="subscriber_new"),
]

mydjango23/mydjango23/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('blog/', include('blog.urls')),
    # FIXME: 아래의 url 설정은 blog 기능 구현 후에 pattern_name으로 변경 예정
    path('', RedirectView.as_view(url='/blog/'), name='root'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include("debug_toolbar.urls")),
    ]

mydjango23/blog/models.py
import tablib
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(TimestampedModel):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Post(TimestampedModel):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, db_index=True)
    content = models.TextField()
    photo = models.ImageField(upload_to="blog/post/%Y/%m/%d")
    tag_set = models.ManyToManyField('Tag', blank=True)
    status = models.CharField(max_length=1,
                              # FIXME: 장고 3에서 추가된 TextChoices 기능을 활용
                              choices=[
                                  ('D', '초안'), # Draft / DB저장값, Label
                                  ('P', '공개'), # Published
                              ],
                              db_index=True,
                              default='D',
                              )

    def __str__(self):
        return self.title

    # post detail 주소 문자열을 반환
    # detail 페이지를 구현하자마자, 즉시 아래 메서드를 구현
    def get_absolute_url(self) -> str:
        return reverse("blog:post_detail", args=[self.pk])

    @classmethod     # 인스턴스 함수를 장식자로 class 로 변경
    def get_tabular_data(cls, queryset, format="xlsx") -> bytes:
        dataset = tablib.Dataset()
        dataset.headers = ["id", "title", "created_at", "updated_at"]

        for post in queryset:
            dataset.append(
                [
                    post.id,
                    post.title,
                    post.created_at.strftime("%Y-%m-%d %H:%M:%S"),
                    post.updated_at.strftime("%Y-%m-%d %H:%M:%S"),
                ]
            )

        return dataset.export(format)


    class Meta:
        ordering = ["-id"]


class Comment(TimestampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()

    def __str__(self):
        return self.message

    class Meta:
        ordering = ["-id"]


class Tag(TimestampedModel):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Subscriber(TimestampedModel):
    phone = models.CharField(
        max_length=15,
        validators=[
            RegexValidator(r"^\d{3,4}-?\d{3,4}-?\d{4}$"),
        ],
    )

mydjango23/blog/forms.py
from django import forms
from blog.models import Post, Tag, Subscriber


class PostForm(forms.ModelForm):
    tags = forms.CharField(required=False)

    # 초기값 지정
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance.pk:
            tag_qs = self.instance.tag_set.all()
            initial = ", ".join([tag.name for tag in tag_qs])
            self.fields["tags"].initial = initial

    # DB로의 저장
    # def save(self, commit=True):
    #     save_post = super().save(commit)
    #     "..."
    #     return saved_post
    # 아래 함수가 호출되기 전에, instance.save()가 호출되었음을 보장받음
    def _save_m2m(self):
        super()._save_m2m()

        tag_list = []
        tags = self.cleaned_data.get("tags", "")
        for word in tags.split(","):
            tag_name = word.strip()
            tag, __ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)

        self.instance.tag_set.clear()
        self.instance.tag_set.add(*tag_list)

    class Meta:
        model = Post
        fields = [
            "category",
            "title",
            "content",
            "photo",
            "status",
        ]


class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = "__all__"

    # Form 만의 유효성 검사 방법
    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        if phone:
            if not phone.startswith("010"):
                raise forms.ValidationError("010으로 시작토록 입력해주세요.")
        return phone.replace("-", "")

mydjango23/blog/views/cbv.py
# Class Based View(CBV)
#   - 뷰 함수를 만들어주는 클래스
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.forms import PostForm
from blog.models import Post, Subscriber

# post_list
post_list = ListView.as_view(
    model=Post,
)

# post_detail
post_detail = DetailView.as_view(
    model=Post,
)


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    # success_url = reverse_lazy("blog:post_list")

    # def get_success_url(self):
    #     # self.object  # 저장된 모델 인스턴스
    #     post_pk = self.object.pk
    #     return reverse("blog:post_detail", args=[post_pk])  # 문자열
        # return resolve_url("blog:post_detail", post_pk)  # 문자열
        # return redirect   ("blog:post_detail", post_pk)  # HttpResponse
        #            {% url "blog:post_detail" post_pk %}  #문자열


# post_new
post_new = PostCreateView.as_view()


class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm

    # def get_success_url(self):
    #     post_pk = self.object.pk
    #     return reverse("blog:post_detail", args=[post_pk])


# post_edit
post_edit = UpdateView.as_view(
    model=Post,
    form_class=PostForm,
    # TODO:가변적으로 URL을 지정할 수 없다.
    # TODO: URL Reverse가 미적용
    # success_url='blog:post_list',  # URL Reverse 미지원
    # success_url=reverse("blog:post_list"),  # 프로젝트가 초기화가 되어야 할 수 있음
    success_url=reverse_lazy("blog:post_list"),
)


# post_delete
post_delete = DeleteView.as_view(
    model=Post,
    success_url=reverse_lazy("blog:post_list"),
)

mydjango23/blog/views/fbv.py
from django.contrib import messages
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView

from blog.forms import PostForm, SubscriberForm
from blog.models import Post, Subscriber


def post_list(request: HttpRequest) -> HttpResponse:
    # print(request.GET)
    # print(request.GET.get("name"))  # dict의 방식
    # print(request.GET["name"])  # dict의 방식 : 중복은 있을 수 없고 한개의 값만 가지고 온다
    # print(request.GET.getlist("name"))  # MultiValueDict에서 지원: 같은 Key의 값을 지원
    post_qs = Post.objects.all()

    format = request.GET.get("format", "")  #  format이라는 이름의 querystring을 가져옴.

    if format == "xlsx":
        tabular_data = Post.get_tabular_data(post_qs, format="xlsx")
        return HttpResponse(tabular_data, content_type="application/vnd.ms-excel")
    elif format == "json":
        tabular_data = Post.get_tabular_data(post_qs, format="json")
        return HttpResponse(tabular_data, content_type="application/json")

    return render(request, "blog/post_list.html", {
        "post_list": post_qs,
    })


def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    return render(request, "blog/post_detail.html", {
        "post": post,
    })


def post_new(request: HttpRequest) -> HttpResponse:
    # request.method  # 'GET','POST'

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            saved_post = form.save()
            messages.success(request, "새로운 포스팅을 저장했습니다.")
            return redirect(saved_post)
            # return redirect("blog:post_detail", saved_post.pk)
    else:
        form = PostForm()

    return render(request, "blog/post_form.html", {
        "form": form,
    })


def post_edit(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_vaild():
            saved_post = form.save()
            messages.success(request, f"#{pk} 포스팅을 저장했습니다.")
            return redirect(saved_post)  # get_absolute_url 이 구현 되어 있을 떄 사용가능
            # return redirect("blog:post_detail", saved_post.pk)
    else:
        form = PostForm(instance=post)

    return render(request, "blog/post_form.html", {
        "form": form,
        "post": post,
    })


def post_delete(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)

    # GET 요청: 정말 삭제를 할 것인지, 한 번 더 물어본다.
    # POST 요청: 삭제를 하고, 다른 주소로 이동을 시킨다.

    if request.method == "POST":
        post.delete()  # 실제로 DB에 DELETE 쿼리 실행
        messages.success(request, f"#{pk} 포스팅을 삭제했습니다.")
        return redirect("blog:post_list")

    return render(request, "blog/post_cnofirm_delete.html", {
        "post": post,
    },)


subscriber_new = CreateView.as_view(
    model=Subscriber,
    form_class=SubscriberForm,
)

mydjango23/blog/templates/blog/layout.html
{% extends "layout.html" %}

{% block extra_head %}
    <style>
    body {
        background-color: lightcoral;
    }
    </style>
{% endblock %}

mydjango23/blog/templates/blog/post_cnofirm_delete.html
{% extends "blog/layout.html" %}


{% block content %}
    <h2>Post 삭제 확인</h2>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="삭제하기"/>
    </form>

    <hr/>

    <a href="{% url "blog:post_detail" post.pk %}">
        detail로 돌아가기
    </a>
{% endblock %}

mydjango23/blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block page_title %}
    {{ block.super }} :: {{ post.title }}
{% endblock %}

{% block content %}
    <h2>{{ post.titls }}</h2>
    
    <p>
    {% for tag in post.tag_set.all %}
        {{ tag.name }}
    {% endfor %}
    </p>

    <img src="{{ post.photo.url }}" alt="{{ post.title }}">

    {{ post.content|linebreaks }}

    <hr/>
    <a href="{% url "blog:post_list" %}">
    포스팅 목록
    </a>

    <a href="{% url "blog:post_edit" post.pk %}">
    포스팅 수정
    </a>

    <a href="{% url "blog:post_delete" post.pk %}">
    포스팅 삭제
    </a>
{% endblock %}

mydjango23/blog/templates/blog/post_form.html
{% extends "blog/layout.html" %}

{% block content %}
    <h2>Post Form</h2>


    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="제출"/>
    </form>

    <hr/>

    <a href="{% url "blog:post_list" %}">
        목록으로
    </a>

    {% if post %}
        <a href="{% url "blog:post_detail" post.pk %}">
            취소
        </a>
    {% endif %}

{% endblock %}

mydjango23/blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}

<h2>Post List</h2>
    <thead>
    {% for post in post_list %}
        <tr>
            <td>
                <a href="{% url "blog:post_detail" post.pk %}">
                    {{ post.title }}
                </a>
            </td>
        </tr>
    {% endfor %}
    </thead>


<hr/>
<a href="{% url "blog:post_new" %}">
    포스팅 쓰기
</a>

{% endblock %}

mydjango23/blog/templates/blog/subscriber_form.html
{% extends "blog/layout.html" %}

{% block content %}
    <h2>Subscriber Form</h2>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" />
    </form>
{% endblock %}